import raylibpy as rl

COLOR_MAP = {
    'LIGHTGRAY': rl.LIGHTGRAY,
    'GRAY': rl.GRAY,
    'DARKGRAY': rl.DARKGRAY,
    'YELLOW': rl.YELLOW,
    'GOLD': rl.GOLD,
    'ORANGE': rl.ORANGE,
    'PINK': rl.PINK,
    'RED': rl.RED,
    'MAROON': rl.MAROON,
    'GREEN': rl.GREEN,
    'LIME': rl.LIME,
    'DARKGREEN': rl.DARKGREEN,
    'SKYBLUE': rl.SKYBLUE,
    'BLUE': rl.BLUE,
    'DARKBLUE': rl.DARKBLUE,
    'PURPLE': rl.PURPLE,
    'VIOLET': rl.VIOLET,
    'DARKPURPLE': rl.DARKPURPLE,
    'BEIGE': rl.BEIGE,
    'BROWN': rl.BROWN,
    'DARKBROWN': rl.DARKBROWN,
    'WHITE': rl.WHITE,
    'BLACK': rl.BLACK,
    'BLANK': rl.BLANK,
    'MAGENTA': rl.MAGENTA,
    'RAYWHITE': rl.RAYWHITE,
}


KEYBOARD_INPUT_MAP = {
    # Letters
    'A': rl.KEY_A, 'B': rl.KEY_B, 'C': rl.KEY_C, 'D': rl.KEY_D, 'E': rl.KEY_E,
    'F': rl.KEY_F, 'G': rl.KEY_G, 'H': rl.KEY_H, 'I': rl.KEY_I, 'J': rl.KEY_J,
    'K': rl.KEY_K, 'L': rl.KEY_L, 'M': rl.KEY_M, 'N': rl.KEY_N, 'O': rl.KEY_O,
    'P': rl.KEY_P, 'Q': rl.KEY_Q, 'R': rl.KEY_R, 'S': rl.KEY_S, 'T': rl.KEY_T,
    'U': rl.KEY_U, 'V': rl.KEY_V, 'W': rl.KEY_W, 'X': rl.KEY_X, 'Y': rl.KEY_Y,
    'Z': rl.KEY_Z,

    # Special
    'SPACE': rl.KEY_SPACE,
    'ENTER': rl.KEY_ENTER,
    'ESCAPE': rl.KEY_ESCAPE,
    'TAB': rl.KEY_TAB,
    'BACKSPACE': rl.KEY_BACKSPACE,
    'LEFT_SHIFT': rl.KEY_LEFT_SHIFT,
    'RIGHT_SHIFT': rl.KEY_RIGHT_SHIFT,
    'LEFT_CONTROL': rl.KEY_LEFT_CONTROL,
    'RIGHT_CONTROL': rl.KEY_RIGHT_CONTROL,
    'LEFT_ALT': rl.KEY_LEFT_ALT,
    'RIGHT_ALT': rl.KEY_RIGHT_ALT,

    # Arrows
    'UP': rl.KEY_UP,
    'DOWN': rl.KEY_DOWN,
    'LEFT': rl.KEY_LEFT,
    'RIGHT': rl.KEY_RIGHT,

    # Function Keys
    'F1': rl.KEY_F1, 'F2': rl.KEY_F2, 'F3': rl.KEY_F3, 'F4': rl.KEY_F4,
    'F5': rl.KEY_F5, 'F6': rl.KEY_F6, 'F7': rl.KEY_F7, 'F8': rl.KEY_F8,
    'F9': rl.KEY_F9, 'F10': rl.KEY_F10, 'F11': rl.KEY_F11, 'F12': rl.KEY_F12,
}

MOUSE_INPUT_MAP = {
    'LEFT': rl.MOUSE_BUTTON_LEFT,
    'RIGHT': rl.MOUSE_BUTTON_RIGHT,
    'MIDDLE': rl.MOUSE_BUTTON_MIDDLE,
    'SIDE': rl.MOUSE_BUTTON_SIDE,
    'EXTRA': rl.MOUSE_BUTTON_EXTRA,
    'FORWARD': rl.MOUSE_BUTTON_FORWARD,
    'BACK': rl.MOUSE_BUTTON_BACK,
}


GAMEPAD_INPUT_MAP = {
    # Raylib standard
    'A': rl.GAMEPAD_BUTTON_RIGHT_FACE_DOWN,
    'B': rl.GAMEPAD_BUTTON_RIGHT_FACE_RIGHT,
    'X': rl.GAMEPAD_BUTTON_RIGHT_FACE_LEFT,
    'Y': rl.GAMEPAD_BUTTON_RIGHT_FACE_UP,

    'LEFT_BUMPER': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_1,
    'RIGHT_BUMPER': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_1,
    'LEFT_TRIGGER': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_2,
    'RIGHT_TRIGGER': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_2,

    'BACK': rl.GAMEPAD_BUTTON_MIDDLE_LEFT,
    'START': rl.GAMEPAD_BUTTON_MIDDLE_RIGHT,
    'GUIDE': rl.GAMEPAD_BUTTON_MIDDLE,

    'DPAD_UP': rl.GAMEPAD_BUTTON_LEFT_FACE_UP,
    'DPAD_DOWN': rl.GAMEPAD_BUTTON_LEFT_FACE_DOWN,
    'DPAD_LEFT': rl.GAMEPAD_BUTTON_LEFT_FACE_LEFT,
    'DPAD_RIGHT': rl.GAMEPAD_BUTTON_LEFT_FACE_RIGHT,

    'LEFT_STICK': rl.GAMEPAD_BUTTON_LEFT_THUMB,
    'RIGHT_STICK': rl.GAMEPAD_BUTTON_RIGHT_THUMB,

    # Xbox-style
    'XBOX_A': rl.GAMEPAD_BUTTON_RIGHT_FACE_DOWN,
    'XBOX_B': rl.GAMEPAD_BUTTON_RIGHT_FACE_RIGHT,
    'XBOX_X': rl.GAMEPAD_BUTTON_RIGHT_FACE_LEFT,
    'XBOX_Y': rl.GAMEPAD_BUTTON_RIGHT_FACE_UP,
    'XBOX_LB': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_1,
    'XBOX_RB': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_1,
    'XBOX_LT': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_2,
    'XBOX_RT': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_2,
    'XBOX_BACK': rl.GAMEPAD_BUTTON_MIDDLE_LEFT,
    'XBOX_START': rl.GAMEPAD_BUTTON_MIDDLE_RIGHT,
    'XBOX_DPAD_UP': rl.GAMEPAD_BUTTON_LEFT_FACE_UP,
    'XBOX_DPAD_DOWN': rl.GAMEPAD_BUTTON_LEFT_FACE_DOWN,
    'XBOX_DPAD_LEFT': rl.GAMEPAD_BUTTON_LEFT_FACE_LEFT,
    'XBOX_DPAD_RIGHT': rl.GAMEPAD_BUTTON_LEFT_FACE_RIGHT,
    'XBOX_LS': rl.GAMEPAD_BUTTON_LEFT_THUMB,
    'XBOX_RS': rl.GAMEPAD_BUTTON_RIGHT_THUMB,

    # PlayStation-style
    'PS_CROSS': rl.GAMEPAD_BUTTON_RIGHT_FACE_DOWN,
    'PS_CIRCLE': rl.GAMEPAD_BUTTON_RIGHT_FACE_RIGHT,
    'PS_SQUARE': rl.GAMEPAD_BUTTON_RIGHT_FACE_LEFT,
    'PS_TRIANGLE': rl.GAMEPAD_BUTTON_RIGHT_FACE_UP,
    'PS_L1': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_1,
    'PS_R1': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_1,
    'PS_L2': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_2,
    'PS_R2': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_2,
    'PS_SHARE': rl.GAMEPAD_BUTTON_MIDDLE_LEFT,
    'PS_OPTIONS': rl.GAMEPAD_BUTTON_MIDDLE_RIGHT,
    'PS_PS': rl.GAMEPAD_BUTTON_MIDDLE,
    'PS_DPAD_UP': rl.GAMEPAD_BUTTON_LEFT_FACE_UP,
    'PS_DPAD_DOWN': rl.GAMEPAD_BUTTON_LEFT_FACE_DOWN,
    'PS_DPAD_LEFT': rl.GAMEPAD_BUTTON_LEFT_FACE_LEFT,
    'PS_DPAD_RIGHT': rl.GAMEPAD_BUTTON_LEFT_FACE_RIGHT,
    'PS_L3': rl.GAMEPAD_BUTTON_LEFT_THUMB,
    'PS_R3': rl.GAMEPAD_BUTTON_RIGHT_THUMB,

    # Nintendo Switch-style
    'SWITCH_B': rl.GAMEPAD_BUTTON_RIGHT_FACE_DOWN,
    'SWITCH_A': rl.GAMEPAD_BUTTON_RIGHT_FACE_RIGHT,
    'SWITCH_Y': rl.GAMEPAD_BUTTON_RIGHT_FACE_LEFT,
    'SWITCH_X': rl.GAMEPAD_BUTTON_RIGHT_FACE_UP,
    'SWITCH_L': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_1,
    'SWITCH_R': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_1,
    'SWITCH_ZL': rl.GAMEPAD_BUTTON_LEFT_TRIGGER_2,
    'SWITCH_ZR': rl.GAMEPAD_BUTTON_RIGHT_TRIGGER_2,
    'SWITCH_MINUS': rl.GAMEPAD_BUTTON_MIDDLE_LEFT,
    'SWITCH_PLUS': rl.GAMEPAD_BUTTON_MIDDLE_RIGHT,
    'SWITCH_HOME': rl.GAMEPAD_BUTTON_MIDDLE,
    'SWITCH_DPAD_UP': rl.GAMEPAD_BUTTON_LEFT_FACE_UP,
    'SWITCH_DPAD_DOWN': rl.GAMEPAD_BUTTON_LEFT_FACE_DOWN,
    'SWITCH_DPAD_LEFT': rl.GAMEPAD_BUTTON_LEFT_FACE_LEFT,
    'SWITCH_DPAD_RIGHT': rl.GAMEPAD_BUTTON_LEFT_FACE_RIGHT,
    'SWITCH_L_STICK': rl.GAMEPAD_BUTTON_LEFT_THUMB,
    'SWITCH_R_STICK': rl.GAMEPAD_BUTTON_RIGHT_THUMB,
}
